CREATE DATABASE IF NOT EXISTS `wallet`;

USE `wallet`;

CREATE TABLE IF NOT EXISTS `mugs` (json LONGTEXT NOT NULL);

CREATE TABLE IF NOT EXISTS `pays` (json LONGTEXT NOT NULL);

CREATE TABLE IF NOT EXISTS `vault` (json LONGTEXT NOT NULL);